#!/usr/bin/env bash

# Based on i3exit

lock() {
   swaylock -f -C ~/.config/swaylock/config
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        swaymsg exit
        ;;
    suspend)
	    lock
        systemctl suspend
        ;;
    hibernate)
	    lock
        systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 [lock|logout|suspend|hibernate|reboot|shutdown]"
        exit 2
esac

exit 0
